#!/usr/bin/env bash
set -euo pipefail

STATE_DIR="${OPENCLAW_STATE_DIR:-/var/lib/openclaw/.openclaw}"
LOG_DIR="${OPENCLAW_LOG_DIR:-/var/log/openclaw}"
STATE_FILE="${STATE_DIR}/ops-health.state"
CHECK_LOG="${LOG_DIR}/health-check.log"
OPENCLAW_HOME="${OPENCLAW_HOME:-/var/lib/openclaw}"
GATEWAY_FAIL_THRESHOLD="${GATEWAY_FAIL_THRESHOLD:-2}"
CHANNEL_FAIL_THRESHOLD="${CHANNEL_FAIL_THRESHOLD:-5}"
DISK_WARN_THRESHOLD="${DISK_WARN_THRESHOLD:-80}"
DISK_CRIT_THRESHOLD="${DISK_CRIT_THRESHOLD:-90}"

mkdir -p "${STATE_DIR}" "${LOG_DIR}"
touch "${CHECK_LOG}"

load_state() {
  gateway_fail_count=0
  channel_fail_count=0
  if [[ -f "${STATE_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${STATE_FILE}" || true
  fi
  gateway_fail_count="${gateway_fail_count:-0}"
  channel_fail_count="${channel_fail_count:-0}"
}

write_state() {
  cat >"${STATE_FILE}" <<STATE
# Auto-generated by health-check.sh
gateway_fail_count=${gateway_fail_count}
channel_fail_count=${channel_fail_count}
last_check=${now}
STATE
}

emit_alert() {
  local level="$1"
  local message="$2"

  logger -t openclaw-ops "[${level}] ${message}"

  if [[ -n "${OPENCLAW_ALERT_WEBHOOK_URL:-}" ]]; then
    if command -v jq >/dev/null 2>&1; then
      local payload
      payload="$(jq -nc --arg level "${level}" --arg message "${message}" --arg ts "${now}" '{level:$level,message:$message,timestamp:$ts,service:"openclaw-gateway"}')"
      curl -fsS -m 10 -H 'content-type: application/json' -d "${payload}" "${OPENCLAW_ALERT_WEBHOOK_URL}" >/dev/null || true
    else
      curl -fsS -m 10 -H 'content-type: application/json' -d "{\"level\":\"${level}\",\"message\":\"${message}\",\"timestamp\":\"${now}\"}" "${OPENCLAW_ALERT_WEBHOOK_URL}" >/dev/null || true
    fi
  fi
}

run_check() {
  local label="$1"
  shift
  if "$@" >>"${CHECK_LOG}" 2>&1; then
    printf '%s %s OK\n' "${now}" "${label}" >>"${CHECK_LOG}"
    return 0
  fi

  printf '%s %s FAIL\n' "${now}" "${label}" >>"${CHECK_LOG}"
  return 1
}

now="$(date -Iseconds)"
load_state

if ! command -v openclaw >/dev/null 2>&1; then
  emit_alert "critical" "openclaw command not found while running health checks"
  exit 2
fi

gateway_ok=1
health_ok=1
channel_ok=1

run_check "gateway_status" openclaw gateway status --json || gateway_ok=0
run_check "health_status" openclaw health --json || health_ok=0
run_check "channel_probe" openclaw channels status --probe || channel_ok=0

if [[ "${gateway_ok}" -eq 1 && "${health_ok}" -eq 1 ]]; then
  gateway_fail_count=0
else
  gateway_fail_count=$((gateway_fail_count + 1))
fi

if [[ "${channel_ok}" -eq 1 ]]; then
  channel_fail_count=0
else
  channel_fail_count=$((channel_fail_count + 1))
fi

disk_pct="$(df -P "${OPENCLAW_HOME}" | awk 'NR==2 {gsub(/%/,"",$5); print $5}')"
if [[ -z "${disk_pct}" || ! "${disk_pct}" =~ ^[0-9]+$ ]]; then
  disk_pct=0
fi

critical=0

if (( gateway_fail_count >= GATEWAY_FAIL_THRESHOLD )); then
  emit_alert "critical" "gateway/health checks failed ${gateway_fail_count} consecutive times"
  critical=1
fi

if (( channel_fail_count >= CHANNEL_FAIL_THRESHOLD )); then
  emit_alert "critical" "channel probe failed ${channel_fail_count} consecutive checks"
  critical=1
fi

if (( disk_pct >= DISK_CRIT_THRESHOLD )); then
  emit_alert "critical" "disk usage at ${disk_pct}% (critical threshold ${DISK_CRIT_THRESHOLD}%)"
  critical=1
elif (( disk_pct >= DISK_WARN_THRESHOLD )); then
  emit_alert "warning" "disk usage at ${disk_pct}% (warning threshold ${DISK_WARN_THRESHOLD}%)"
fi

write_state

if (( critical == 1 )); then
  exit 2
fi

exit 0
