#!/usr/bin/env bash
set -euo pipefail

STATE_DIR="${OPENCLAW_STATE_DIR:-/var/lib/openclaw/.openclaw}"
LOG_DIR="${OPENCLAW_LOG_DIR:-/var/log/openclaw}"
STATE_FILE="${STATE_DIR}/ops-restart-watch.state"
WATCH_LOG="${LOG_DIR}/restart-watch.log"
RESTART_WARN_THRESHOLD="${RESTART_WARN_THRESHOLD:-3}"

mkdir -p "${STATE_DIR}" "${LOG_DIR}"
touch "${WATCH_LOG}"

emit_alert() {
  local level="$1"
  local message="$2"
  local now
  now="$(date -Iseconds)"

  logger -t openclaw-ops "[${level}] ${message}"

  if [[ -n "${OPENCLAW_ALERT_WEBHOOK_URL:-}" ]]; then
    if command -v jq >/dev/null 2>&1; then
      local payload
      payload="$(jq -nc --arg level "${level}" --arg message "${message}" --arg ts "${now}" '{level:$level,message:$message,timestamp:$ts,service:"openclaw-restart-watch"}')"
      curl -fsS -m 10 -H 'content-type: application/json' -d "${payload}" "${OPENCLAW_ALERT_WEBHOOK_URL}" >/dev/null || true
    else
      curl -fsS -m 10 -H 'content-type: application/json' -d "{\"level\":\"${level}\",\"message\":\"${message}\",\"timestamp\":\"${now}\"}" "${OPENCLAW_ALERT_WEBHOOK_URL}" >/dev/null || true
    fi
  fi
}

if ! command -v systemctl >/dev/null 2>&1; then
  echo "systemctl not available; skipping restart watch" >>"${WATCH_LOG}"
  exit 0
fi

current_total="$(systemctl show -p NRestarts --value openclaw-gateway.service 2>/dev/null || echo 0)"
if [[ -z "${current_total}" || ! "${current_total}" =~ ^[0-9]+$ ]]; then
  current_total=0
fi

previous_total=0
previous_epoch=0

if [[ -f "${STATE_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${STATE_FILE}" || true
  previous_total="${previous_total:-0}"
  previous_epoch="${previous_epoch:-0}"
fi

now_epoch="$(date +%s)"
now="$(date -Iseconds)"

delta=$((current_total - previous_total))
if (( delta < 0 )); then
  delta=0
fi

printf '%s restarts_total=%s delta_since_last=%s\n' "${now}" "${current_total}" "${delta}" >>"${WATCH_LOG}"

if (( previous_epoch > 0 )) && (( now_epoch - previous_epoch <= 5400 )) && (( delta > RESTART_WARN_THRESHOLD )); then
  emit_alert "warning" "openclaw-gateway restarted ${delta} times in the last hour"
fi

cat >"${STATE_FILE}" <<STATE
# Auto-generated by restart-watch.sh
previous_total=${current_total}
previous_epoch=${now_epoch}
STATE

exit 0
